sudo: required

language: bash

services:
- docker

install:
- docker pull swipl:stable

script:
- docker run -it --name test --entrypoint=/bin/bash library/swipl -c "logtalk_user_setup && cd ~/logtalk/tests/logtalk && logtalk_tester"
