sudo: required

language: bash

services:
- docker

before_install:
- docker pull logtalk/logtalk3-swi-nightly
- docker ps -a
- docker run -it --name test --entrypoint=/bin/bash logtalk/logtalk3-swi-nightly

script:
- bash logtalk_user_setup
- bash cd /logtalkuser_prefix/logtalk/tests/logtalk && logtalk_tester
