sudo: required

language: bash

services:
- docker

install:
- docker pull swipl:stable

script:
- docker run -it --name test --entrypoint=/bin/bash -v ${PWD}:/logtalk3 library/swipl -c "/logtalk3/scripts/install.sh && logtalk_user_setup && cd ~/logtalk/tests/logtalk && logtalk_tester"
